apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3 # Set the number of replicas as needed
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: awabamjad/wordreversalfrontend:latest # Docker Hub image
          ports:
            - containerPort: 80 # Port your app runs on inside the container
