apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # Port your service will listen on
      targetPort: 80 # Port your app listens on inside the container
